# Generated by Django 2.0.2 on 2018-06-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180625_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['publication_date']},
        ),
    ]
