# Generated by Django 2.0.2 on 2018-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180704_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, editable='True', height_field='height_field', null=True, upload_to='blog/mediacdn/', width_field='width_field'),
        ),
    ]
