# Generated by Django 2.0.2 on 2018-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180704_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, editable='True', height_field='height_field', null=True, upload_to='blog_project/mediacdn/', width_field='width_field'),
        ),
    ]
