# Generated by Django 2.0.2 on 2018-07-05 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180704_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 18, 58, 42, 862641, tzinfo=utc)),
        ),
    ]
