# Generated by Django 2.0.2 on 2018-07-08 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180705_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 10, 49, 41, 598267, tzinfo=utc)),
        ),
    ]
