# Generated by Django 2.0.2 on 2018-07-08 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180708_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 11, 3, 44, 29420, tzinfo=utc)),
        ),
    ]
